### ISSUE TITLE
Unknown element closes the current paragraph and becomes a block-level element when at the first column

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#231]
One thing that irritated me when I started moving kramdown-rfc2629 to kramdown 1.6.0:

```markdown
This is a paragraph with some needless raw XML in it <xref format="counter"
target="introduction"/>.  This works well, until we start it on a new line:
<xref format="counter" target="introduction"/> Here we get block-level element!
```

vs.

```markdown
This is a paragraph with some needless raw XML in it <xref format="counter"
target="introduction"/>.  This works well, until we start it on a new line:
x <xref format="counter" target="introduction"/> Here we get block-level element!
```
(note the x in the second example that seems to turn the xref from block-level to span-level).

Can I declare xref (and a ton of other things) to always be span-level?

**Comment by gettalong** [comment]
Is the behaviour different from previous versions of kramdown?

**Comment by cabo** [comment]
It certainly is different from 1.4.x and Ruby 2.1.  I'll investigate more...

**Comment by cabo** [comment]
Ah, I was confused by an intermediate gem I installed.  Yes, this is between 1.5.0 and 1.6.0:

```
$ cat ~/tmp/kram231.mkd
This is a paragraph with some needless raw XML in it <xref format="counter"
target="introduction"/>.  This works well, until we start it on a new line:
<xref format="counter" target="introduction"/> Here we get block-level element!
$ kramdown ~/tmp/kram231.mkd
<p>This is a paragraph with some needless raw XML in it <xref format="counter" target="introduction"></xref>.  This works well, until we start it on a new line:</p>
<xref format="counter" target="introduction" />
<p>Here we get block-level element!</p>
$ kramdown _1.5.0_ ~/tmp/kram231.mkd
<p>This is a paragraph with some needless raw XML in it <xref format="counter" target="introduction"></xref>.  This works well, until we start it on a new line:
<xref format="counter" target="introduction"></xref> Here we get block-level element!</p>
$
```

**Comment by cabo** [comment]
63c0da5, maybe?

**Comment by gettalong** [comment]
Thanks for the digging, I will have a look at it!

**Comment by cabo** [comment]
Just to make sure I'm making myself clear: I think the new behavior is fine, it just requires me much more to make the span-level-ness of some elements known to the kramdown parser.

**Comment by gettalong** [comment]
Okay, I have more time tomorrow to look a this but the commit you mentioned was the reason for this different behaviour, also see #220:

~~~
$ cat test.md
test
<xref>test</xref>

test
<xref a="b">test</xref>

kramdown-1.5.0 $ kramdown test.md
<p>test</p>
<xref>test</xref>

<p>test
<xref a="b">test</xref></p>

kramdown-1.6.0 $ kramdown test.md
<p>test</p>
<xref>test</xref>

<p>test</p>
<xref a="b">test</xref>
~~~

As you can see there was a different behavior depending on whether the XML had attributes or didn't have attributes.

FYI: The current behavior follows the syntax definition (http://kramdown.gettalong.org/syntax.html#html-blocks).

**Comment by cabo** [comment]
Starting my parser like this seems to fix the specific test case:

```ruby
module Kramdown

  module Parser

    class Kramdown
      # monkey-patch...
      HTML_SPAN_ELEMENTS << "xref"
      LAZY_END_HTML_SPAN_ELEMENTS = HTML_SPAN_ELEMENTS + %w{script}
    end

    class RFC2629Kramdown < Kramdown
```

(Obviously, I need to add all my span elements and not just this one.)

I probably don't have to mention that I'd prefer an official interface for doing this to this monkey patch...

**Comment by gettalong** [comment]
If this is only needed for kramdown-rfc2629, you could do the following:

~~~ ruby
require 'kramdown'
Kramdown::Parser::Html::Constants::HTML_SPAN_ELEMENTS << "xref"
~~~

Note that this needs to be done **before** the kramdown parser is loaded, otherwise the constant has already been used to create the necessary regexp.

There is currently no other way to do this in any other manner.

Since the behavior is now consistent regardless of whether the XML element uses attributes and it follows the syntax rules, changing this to do something else is probably not a good idea.

**Comment by cabo** [comment]
Again, I agree that the change towards this behavior is fine; I'm just trying to find a sustainable way to add span elements.
Sorry, I don't get your above proposal:
`require 'kramdown'` already loads the kramdown parser.

The funny thing is that my above code (or actually the slightly less brittle version below) does work for me.

```ruby

module Kramdown

  module Parser

    class Kramdown      # monkey-patch the span elements to work around #231 for now:
      my_span_elements =  %w{list figure xref eref iref cref spanx vspace}
      HTML_SPAN_ELEMENTS.concat my_span_elements
      # LAZY_END_HTML_SPAN_ELEMENTS.concat my_span_elements
    end
```

(Yes, the lazy stuff is commented out, and it still seems to work.)

**Comment by gettalong** [comment]
No, `require 'kramdown'` doesn't load the file with the kramdown parser because it is autoloaded. 

Your solution is working similar to my proposed one but they are not the same:

* When you access the `Kramdown::Parser::Kramdown` constant, the files to be autoloaded are loaded and evaluated. Then you change the `HTML_SPAN_ELEMENTS` constant. This means that the used regexp is not changed.

* In my solution, only the HTML parser is loaded, the `HTML_SPAN_ELEMENTS` constant updated and when the kramdown parser is later loaded the regexp is correctly set.

However, since parsing is iterative and there is a provision for concatenating paragraphs your solution works, too.

Alas, as I said, I can't provide you with a clean solution at the moment.

**Comment by cabo** [comment]
Ah, got it.
I installed your code (with all the actual span elements added) as a workaround for now to minimize breakage.
