### ISSUE TITLE
Gets confused about different "code" style types

### ISSUE THREAD

**Issue by Pinwheeler** [gettalong/kramdown#236]
I'm trying to parse a .yml file using kramdown and I'm having trouble getting it to format elegantly. Using the following text (ignore the backslashes, I couldn't get github markdown to ignore my tildes):

```
\~\~\~
level_1:
  level_2:
  - url: https://site.com/path/to/your//url
\~\~\~
```

I am getting an output that adds extra indentation starting a level_2. I think this might be because Kramdown uses indentation to identify code blocks and doesn't avoid applying this rule to code denoted with the '~' character.

**Comment by gettalong** [comment]
This has probably something to do with the program you are using and not kramdown itself as the kramdown binary produces the correct output:

~~~
<pre><code>level_1:
  level_2:
  - url: https://site.com/path/to/your//url
</code></pre>
~~~

Do you have some more information? Like the toolchain your are using or an example output showing the wrong behavior?

**Comment by Pinwheeler** [comment]
Yeah, here's the html as rendered by chrome with the code that I posted earlier

```html
<pre><code>level_1:
                  level_2:
                  - url: https://site.com/path/to/your//url
                </code></pre>
```

**Comment by gettalong** [comment]
I don't think that this is kramdown's fault. Which toolchain are you using?

**Comment by Pinwheeler** [comment]
I'm not sure how to answer that question. I think that you are asking what technologies are being used in this project. As far as I'm aware it's RoR, Bootstrap, Backbone, posgresql, and haml

**Comment by gettalong** [comment]
With toolchain I meant how kramdown is used to generate the output. One possible toolchain would be direct use of kramdown, another use would be through another library like HAML.

As far as I can tell this problem has nothing to do with kramdown. From your list I think that maybe HAML might be the problem because HAML does do indentation and may invalidly indent the second and the following lines of the code block.

It definitely doesn't have anything to do with the two different styles of codeblocks that are available as markup syntax.

**Comment by Pinwheeler** [comment]
Interesting! I'll look into resolving the HAML confusion. Sorry to have assumed so much

**Comment by gettalong** [comment]
No problem! However, I have to little information to pinpoint the problem, it *might* be HAML's use of kramdown but it can also be something else.
