### ISSUE TITLE
Support "-" (dash) in name of code block lang

### ISSUE THREAD

**Issue by dg-ratiodata** [gettalong/kramdown#244]
Hi @gettalong,

are you going to accept a PR which makes it possible to use a dash in the code block language?

    ~~~ mermaid-graph
    ~~~

Maybe it's just this [line](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/kramdown/codeblock.rb#L35) which needs to be changed to

```ruby
FENCED_CODEBLOCK_MATCH = /^((~){3,})\s*?(\w+-)?\s*?\n(.*?)^\1\2*\s*?\n/m
```

**Comment by gettalong** [comment]
Yes, I would accept it. I still have to have a look at the code to determine if this would have a side effect but I don't think so.

The change should be backwards-compatible because valid fenced code blocks are not affected.

**Comment by maxmeyer** [comment]
I opened a new PR using my private account.

**Comment by gettalong** [comment]
@maxmeyer  Just one question before we go further: Wouldn't it be easier to just use an underscore instead of a dash in your custom language? Or is there another reason?

**Comment by maxmeyer** [comment]
> Wouldn't it be easier to just use an underscore instead of a dash in your custom language? 

To make it short: It's a reason for style and maybe compatibility with concurrent frameworks.

I would like to integrate [mermaid](https://github.com/knsv/mermaid) into [middleman-presentation](https://github.com/fedux-org/middleman-presentation) via "code blocks":

    ~~~
    graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
    ~~~

I'm using a [custom kramdown code block converter](https://github.com/fedux-org/middleman-presentation/blob/95d55cebe43f3a961771185ea692e906ae1ec62a/middleman-presentation-core/lib/middleman-presentation-core/syntax_highlighter.rb) already so I'm able to generate the HTML stuff in a way I need. 

Using code blocks raise a problem "for me": What if a user wants to highlight the mermaid code instead of rendering a graph? It looks like the guys over [here](https://github.com/hakimel/reveal.js/issues/1082) decided to use something like this to make it possible:

    ~~~ mermaid-graph
    graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
    ~~~

Personally I like the `mermaid-graph`-thing because I use the dash as delimiter and the underscore where text belongs together but whitespace cannot be used: "20140101-this_is_a_text"

**Comment by maxmeyer** [comment]
BTW:
There seem to be some [programming languages](http://en.wikipedia.org/wiki/List_of_programming_languages) in the wild whose name include a dash. `middleman-presentation` depends on [`highlight.js`](https://highlightjs.org/) for syntax highlighting. If the developers add one of those languages it could not be used with `middleman-presentation`. And as I'm very happy with `kramdown`, I don't want to switch the `markdown`-parser.

**Comment by gettalong** [comment]
Okay, thanks for explaining your reasons.

**Comment by gettalong** [comment]
Thanks for everything, your changes from #246 are now in master.
