### ISSUE TITLE
Ignore certain tags?

### ISSUE THREAD

**Issue by Carpetsmoker** [gettalong/kramdown#272]
Is there any way to ignore certain tags? I use Kramdown to send emails, and some things like headers aren't very useful there, and more likely to be used by accident rather than anything else.

I now use:

	# A 'trimmed down' Mardown without headers, codeblocks, tables, codespans, and
	# footnotes.
	#
	# You can use it "automatically" with:
	#
	#   Kramdown::Document.new(text).to_html_light
	class HtmlLight < Kramdown::Converter::Html
		# A no-op that just returns the Markdown source
		def noop el, indent
			return el.value.to_s + el.children.map { |c| c.value.to_s }.join('')
		end

		alias_method :convert_header, :noop
		alias_method :convert_codeblock, :noop
		alias_method :convert_table, :noop
		alias_method :convert_codespan, :noop
		alias_method :convert_footnote, :noop
	end

Which *almost* works, except that it loses the text that triggered the tag. So

	Header
	======
	**text**

becomes:

	header
	<p><strong>text</strong></p>

instead of:

	header<br>
	==========
	<p><strong>text</strong></p>

**Comment by gettalong** [comment]
This is not possible with your current approach because the characters used for describing the syntax (like the underlines for a header) are consumed by the parser and not represented.

It would be better to create a custom parser that just doesn't use the header syntax and all other syntaxes you don't want. Have a look at the source of the GFM parser to see how such a parser could be written. It's more or less just removing some items from two arrays.

**Comment by Carpetsmoker** [comment]
Thanks :-)

Here's what I ended up using, perhaps it's useful to someone else:

	#!/usr/bin/env ruby

	require 'kramdown'

	class Kramdown::Parser::Light < Kramdown::Parser::GFM
			IGNORE = [:setext_header, :atx_header, :codeblock, :table, :codespan,
					:footnote_definition, :footnote_marker]

			def initialize source, options
					super
					@block_parsers.delete_if { |i| IGNORE.include? i }
			@span_parsers.delete_if { |i| IGNORE.include? i }
			end
	end

	puts Kramdown::Document.new(File.read('test.markdown'), {
			input: :light
	}).to_html

The keys to remove are what are added with `define_parser()`.
