### ISSUE TITLE
Unicode support for footnote definition

### ISSUE THREAD

**Issue by mehdisadeghi** [gettalong/kramdown#281]
Since I write using non-ASCII characters, I realized it is not allowed to use non-ASCII footnote definitions such as `[^پانویس]`. So, here is the request to add Unicode support to them.

Ruby supports Unicode [pretty well](http://ruby-doc.org/core-1.9.3/Regexp.html#class-Regexp-label-Character+Properties) so it is basically possible.

**Comment by gettalong** [comment]
The current definition for footnote marker names requires them to only include "word characters, digits or dashes" - see http://kramdown.gettalong.org/syntax.html#footnotes.

Since changing this behavior could potentially change the output of existing documents, I'm reluctant to add support for other characters in footnote marker names.

However, a new major version of kramdown can certainly include this.

**Comment by cabo** [comment]
Hmm.  Explain how پانویس are not word characters.  Oh, you don't allow any beyond-ASCII characters here.  Maybe that can be changed without too much of a backwards compatibility issue if you limit it to word characters (Unicode letters, or maybe even /[[:word:]]/ - A character in one of the following Unicode general categories Letter, Mark, Number, Connector_Punctuation).

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1
