### ISSUE TITLE
Anchors of multiple code blocks have duplicates

### ISSUE THREAD

**Issue by MartinThoma** [gettalong/kramdown#302]
Kramdown / GFM with the name and id `n[line number]` to fenced code blocks (e.g. [here](https://martin-thoma.com/analyzing-pypi-metadata-2/#n1)). However, when there are two fenced code block both get this naming scheme.

**The problem**: Obviously, this results in duplicate ids / anchors not working.

**The fix**: For every code block except the first, use the naming scheme `n[line number]-[code block]` or something similar. I suggest to exclude the first one to prevent existing links from breaking.

**Comment by gettalong** [comment]
Please provide a small example (input, current output, expected output) as I don't fully understand your question. Furthermore kramdown does **not** generate names and IDs for fenced code blocks.

**Comment by MartinThoma** [comment]
@gettalong Kramdown+GFM does not generate the line numbers? But I've only got them in my Jekyll block since I changed from recarpet to Kramdown+GFM. That's strange.

Is there a way to execute kramdown with GFM via command line directly?

**Comment by gettalong** [comment]
Ah, it seems that you are using coderay as syntax highlighter which numbers lines per default and also assigns names in `<a>` links. Since the highlighting is done by coderay you have to look to coderay for a solution.

Judging from the website http://coderay.rubychan.de/doc/CodeRay/Encoders/HTML.html you need to use the `:line_number_anchors` option to fix this.

**Comment by gettalong** [comment]
I guess the question was answered, if not please comment again.

**Comment by MartinThoma** [comment]
It was answered and my problem is fixed. Thank you very much!
