### ISSUE TITLE
Empty link text

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#305]
Commonmark allows link text to be empty:

http://spec.commonmark.org/0.24/#links

kramdown doesn't: `[](#)` is not recognized and rendered literally.

Now this has been the case for a long time (apparently, it drove me to define special syntax for RFCXML xrefs in 2010 or so).

Still, I'd like to understand the rationale for this, and, if it turns out to be weak, discuss whether this behavior can be changed to be more like commonmark.

(There are legitimate uses of empty link text [even in HTML](http://yuiblog.com/blog/2008/01/23/empty-links/), but I'm mainly interested in using this for kramdown-rfc2629.)

**Comment by gettalong** [comment]
As per the [syntax spec](http://kramdown.gettalong.org/syntax.html#inline-links) at least one character needs to be inside the square brackets.

However, it seems that most implementations do allow this, even the original Markdown.pl implementation, see http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%5D(%23).

As for a rationale: I don't think I had any, it probably just seemed the right way to do.

So I would classify this as a bug since even for images it works okay in kramdown.
