### ISSUE TITLE
Kramdown unsupported on GitHub Pages HTML tag

### ISSUE THREAD

**Issue by YixuanFranco** [gettalong/kramdown#308]
It works fine usually.

But I just follow the GitHub's warning, and changed my `_config.yml`

markdown:            kramdown
highlighter:         rouge

then the html code in my blog can't recognize this...

```<embed autostart=”true” hidden=”false” loop=-1 src=”http://openmindclub.qiniudn.com/Yixuan/music/pack.mp3”></embed>```

[what is like in my blog](http://yixuan.li/yixuan/2015/12/05/places2/)

**Comment by shellscape** [comment]
getting the same on our blog, html inline is no longer recognized and is being escaped in output

**Comment by YixuanFranco** [comment]
@shellscape sigh, this is terrible...
Btw, your website looks pretty nice.

**Comment by gettalong** [comment]
Inline HTML is supported but only correct XHTML, not any of the various HTML5 allowed syntaxes.

In your example the `loop=-1` is wrong, it should be `loop="-1"` and it seems that the quotation marks are fancy ones instead of the straight ones (at least in your example, I didn't look at your blog in detail).

**Comment by shellscape** [comment]
@gettalong might've been slightly premature to close this one. we've run into it in various places, specifically as an example:

```html
<p align="center">
  <img src="..."/>
</p>
```

The result is that the image tag is escaped, but the paragraph tag is not.

Your comment about XHTML brings up another related point: why would XHTML be the only supported syntax of HTML, given that XHTML as a standard is seldom used or recommended for the doctype of sites anymore?

**Comment by gettalong** [comment]
If I run the kramdown binary with your sample as input, the output is exactly the same as the input. I.e. with your given input the output from kramdown is correct.

As for XHTML: kramdown uses a custom HTML parser so that some things like kramdown markup inside HTML tags work correctly. And the easiest implementation of an HTML parser is an XHTML parser. Note, however, that the parser allows some simple "errors" like `<br>` instead of `<br />`. Anything more complex is not supported.
