### ISSUE TITLE
ID value of heading with unicode characters

### ISSUE THREAD

**Issue by thecotne** [gettalong/kramdown#321]
`transliterated_header_ids` is terribly wrong!

unicode characters are supported in url and in `id` attribute
this is how redcarpet does this https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L274

it's just removes unsafe characters and that's all

i have switched from redcarpet because of github pages update

**Comment by gettalong** [comment]
See https://www.w3.org/TR/html4/types.html on the reason behind the restriction when specifying IDs in kramdown via the header-id feature, the ID shortcut in attribute lists or by using auto-ids. Only since HTML5 any value is allowed in an ID attribute.

You can always set an ID to any value using an IAL like `{:id="äüöæœøá"}`.

Changing the auto-id-generation at this point would cripple many existing sites using kramdown.

**Comment by thecotne** [comment]
this can be optional for backfard compatibility.
but this is how redcarpet worked and many sites that used redcarpet on github pages. 
besides that it's more correct way of creating ids since unicode chars are supported

**Comment by gettalong** [comment]
If you like to have this feature, I will consider merging a pull request that implements this as a new option, similar to auto_id_stripping.

**Comment by thecotne** [comment]
i am not sure if i can develop this feature my self since i am not ruby developer 

so if you consider implementing this here is implementation in some other languages
c: https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L274
javascript: https://github.com/thecotne/core/blob/master/js/lib/utils/string.js#L23
php: https://github.com/thecotne/core/blob/master/src/Util/Str.php#L23
