### ISSUE TITLE
Ruby variables within link syntax

### ISSUE THREAD

**Issue by kylesimmonds** [gettalong/kramdown#347]
This may be beyond the scope of Kramdown, but I'm trying to use a Ruby variable within a Kramdown link:

I've tried ERB (using a static-site generator):
`[link text](<%= $variable %>/path)`

Interpolation:
`[link text](#{$variable}/path)`

And, as a last-ditch effort, just throwing the variable in there:
`[link text]($variable/path)`

Is there a way to do this within the Kramdown syntax?

**Comment by gettalong** [comment]
It all depends on what you are actually doing.

Are you using kramdown with *just* ERB? Do ERB processing first and and then kramdown processing (will work since no special ERB tags are left over to confuse kramdown).

If you are using kramdown within a larger framework like a static website generator, use the tools of the framework.

kramdown itself just processes text markup and has no notion of a template language or variables. And that is on purpose.

**Comment by kylesimmonds** [comment]
@gettalong gotcha, so the processing order is what matters when using a framework. In this case, I'm using Nanoc and Kramdown filtering was happening before everything else. Adding the ERB filter before Kramdown fixed it.

Thanks!
