### ISSUE TITLE
GFM newline before ending code block

### ISSUE THREAD

**Issue by michaelmccaskill** [gettalong/kramdown#360]
Ending a code block with a newline before it causes the rendering to use two `<p>` blocks with escaped triple backticks. Removing the newline gives expected behavior. Interestingly leaving the newline in still produces correct HTML for the Atom markdown preview and in GitHub.

>\```
>cd ../../..
>
>\```

Produces

```
<p>```
cd ../..</p>

<p>```</p>
```

**Comment by gettalong** [comment]
I don't get the same results.

When using fenced code blocks with kramdown (i.e. the standard tildes instead of the GFM backticks) it works (using the command `kramdown`) and results in:

~~~ html
<pre><code>cc ../../..

</code></pre>
~~~

When using kramdown in GFM mode with your original input, the command `kramdown -i GFM` gives the same result:

~~~ html
<pre><code>cd ../../..

</code></pre>
~~~

What did you do to get the wrong result?

**Comment by michaelmccaskill** [comment]
I'm not sure exactly what's going on. It's being invoked via awestruct but I did run it multiple times to verify it is happening. I'll see about running kramdown directly and seeing what happens.

**Comment by michaelmccaskill** [comment]
So I installed kramdown 1.11.1 locally and tried with a test file that only includes the data above and I still get:

\<p>```
cd ../../..</p>

\<p>```</p>

I'm on OS X 10.11.6 using brew ruby 2.3.2 if that helps.

**Comment by gettalong** [comment]
If you want to use GFM style fenced codeblock with backticks instead of tildes, you have to use the GFM parser, like I did by using the command line option `-i GFM`. Otherwise only the standard tildes are recognized as fenced codeblock boundaries.

I.e. if the test file is called `test.md`, do the following:

~~~
$ kramdown -i GFM test.md
<pre><code>cd ../../..

</code></pre>
$
~~~

**Comment by michaelmccaskill** [comment]
Ah ok sorry about that. Just for kicks I tried it with redcarpet and it gives me to same result. But I confirmed your solution works. So it looks like the problem is with Tilt and/or Awestruct, not kramdown. Thanks.

**Comment by gettalong** [comment]
No problem, glad I could help.
