### ISSUE TITLE
lists with nested code blocks are parsed incorrectly

### ISSUE THREAD

**Issue by dalexj** [gettalong/kramdown#366]
if you create an ordered list with some nested information, the ordered list closes and reopens the \<ol> tags, which screw up the numbering of the list.

For example, here is some markdown and the github-parsed view of it below:

```

1. item in list

    ```
code
code
    ```

2. another item in list

```

========
github version:

1. item in list

    ```
code
code
    ```

2. another item in list

**Comment by gettalong** [comment]
If the result you want is to have a codeblock inside the first list item, you need to use the correct indentation for the codeblock markers which is three spaces for your example.

Also note that kramdown uses three tildes for a fenced codeblock. If you want to use backticks you have to use the GFM parser instead of the standard kramdown parser.
