### ISSUE TITLE
with Jekyll: HTML code generated to include a SVG is broken

### ISSUE THREAD

**Issue by oncleben31** [gettalong/kramdown#373]
I've post this issue first in Jekyll/minima repository in issue jekyll/minima#40 then in Jekyll/Jekyll in the issue https://github.com/jekyll/jekyll/issues/5438. It seems directly related to kramdown, so I post it here hoping someone will find a solution.
I was trying to add a SVG from creativecommons.org to a page in Jekyll and there were inconsistencies during the building.
I know there is a workaround by cleaning the SVG file but the question is do kramdown should be able to process the original SVG without error.

## My Reproduction Steps

Starting from a fresh install of jekyll with minima theme. 
*   Download the [svg file](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg) in `_includes` folder
*   create a snippet `icon-cc-by-nc-sa_bug.html` in the `_includes`folder with following code:
```html
<a href="https://creativecommons.org/licenses/by-nc-sa/3.0/fr/">{% include by-nc-sa.svg %}</a>
````
*   create a post with the following code in a .md file:
```markdown
---
layout: post
title:  "Test du bug SVG"
date:   2016-09-18 00:12:00 +0000
categories: bug
---
{% include icon-cc-by-nc-sa_bug.html %}
```
*   build with jekyll

The HTML code generated by jekyll adds 2 tags at the wrong place (`</a></p>`) and break the HTML code consistency: a `</a>` appear and the link doesn't work.
![svg_bug](https://cloud.githubusercontent.com/assets/93244/18618116/02e7062e-7de0-11e6-9bfa-db437da46025.jpg)
![test_bug_svg_html_ __users_administrateur_dev_oncleben31cc-vm_my-blog](https://cloud.githubusercontent.com/assets/93244/18618220/7fcad844-7de2-11e6-8aeb-3f2698e9b693.jpg)

## The Output I Wanted

The code generated by Jekyll should create a consistent html page.

**Comment by pathawks** [comment]
Kramdown chokes when processing an SVG that is not inside a block HTML tag:

```html
<a href="#"><svg xmlns="http://www.w3.org/2000/svg">
<g>
</g>
</svg>
</a>
```

Generates the following:

```html
<p><a href="#"><svg xmlns="http://www.w3.org/2000/svg"></svg></a></p>
<g>
</g>
<p>&lt;/svg&gt;
&lt;/a&gt;</p>
```

Notice how the `<svg>` element is closed before the `<g>` element. Also, the `<a>` and `<p>` are also closed early. So then the _real_ closing tags are just escaped and displayed.

This problem does _not_ happen when the original document is wrapped in `<p>`:

```html
<p>
<a href="#"><svg xmlns="http://www.w3.org/2000/svg">
<g>
</g>
</svg>
</a>
</p>
```

Also, the problem does not happen when the `<a>` is removed:

```html
<svg xmlns="http://www.w3.org/2000/svg">
<g>
</g>
</svg>
```

**Comment by gettalong** [comment]
@oncleben31 Thanks for reporting this issue! However, since we need to eliminate all possible external problems like Jekyll you need to provide a kramdown-only testcase.

Could you please provide a kramdown document that produces the erroneous HTML when converted using the kramdown binary?

**Comment by gettalong** [comment]
@pathawks Ah, didn't have your post in the browser before I posted...

The problem here is that SVG is based on XML and kramdown tries to parse it. When it sees the `<a>` tag, it starts a paragraph since in kramdown documents, links can only appear inside a paragraph. The `<svg>` tag is then parsed as an raw XML tag.

However, paragraph parsing is based on lines and a paragraph ends when an HTML or XML block starts. Since the non-HTML tag `<g>` is not an HTML inline element tag, it concludes that the paragraph must be over and closes all currently open HTML/XML tags to create a valid document. Therefore the trailing `<svg>` and `<a>` tags are escaped.

If you make sure that the SVG image doesn't have any line breaks so that the kramdown parser doesn't leave paragraph parsing mode, you will be fine:

~~~
$ kramdown
<a href="#"><svg xmlns="http://www.w3.org/2000/svg"><g></g></svg></a>
^D
<p><a href="#"><svg xmlns="http://www.w3.org/2000/svg"><g></g></svg></a></p>
~~~
