### ISSUE TITLE
create a new type 

### ISSUE THREAD

**Issue by luisbritescarvalho** [gettalong/kramdown#397]
I'm using a markdown parser and a html converter. I would like to add a new type called "x". The goal is, if the markdown has something like `<x>id</x>` it should return a custom html. 

What I was expecting was to override the html converter and add a converter_x, but that's not enough. How can I create a new type? 

Thanks in advance for your help!

**Comment by gettalong** [comment]
An element type is just a symbolic name assigned to `Element#type`, so you would just need to create an element with your type `:x`. To do this create a parser based on the kramdown parser that creates this new element type based on some syntax you define, and then update the converters so that they understand it. See the source code and API documentation for more information.
