### ISSUE TITLE
how to change parsing of nested lists and code blocks

### ISSUE THREAD

**Issue by nvoynov** [gettalong/kramdown#398]
Hi, @gettalong 

At first, thanks for your passion of my naive questions and I have the latest one. Does kramdown have options that can change parsing of code blocks and nested lists? 

I think it need to be explained origin of my questions. I have few old and large markdown documents (actually, each of this large files is a subset of smallest one, and built into one large document). All this documents created through Atom editor. 

- All code blocks in this files are written through ```language, some of these have an empty line before and some have not. 
- All nested lists have two space indentation and maximum three levels of nesting. 
- All this documents display and save to html correctly in Atom. 
- Earlier, I used GitBook to serve this files for its audience and GitBook displays this files correctly also.

A week ago, I decided to write my own small Sinatra application to serve this old documents and all new documents in future. And I chose RecCarpet at first. But it find out that have a strange bug with some tables and didn't get any answers, and then I found kramdown that is more interesting because of lots small extensions (especially, I chose it because of {#header-links} extension, it's very helpful to make cross-files links). 

I meet a lot of small fights on my attempts to adopt my old markdown documents to kramdown. I coded htlm_toc, replaced code blocks from ```language to `~~~ language`, and now I'm replacing two space indentation to three spaces indentation ...

Have you ever thought to reduce restriction on the file format, make it a bit less strict?

**Comment by gettalong** [comment]
No and yes.

No, because the kramdown parser is designed to parse a certain syntax, without options to change the way parsing is done. The reason for this is that it should be possible to write a kramdown document and later parse it, without special knowledge of options that need to be enabled to do so.

Yes, because you can subclass the kramdown parser class and change whatever you like.

As for the file format: You can view it as strict or you can view it as predictable and (mostly) coherent. However you view it, it is as it is. Other Markdown libraries probably have a more relaxed interpretation but it is hard to predict the correct output for them.
