### ISSUE TITLE
Consecutive markdown lists are joined to one list

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#407]
```
$ kramdown
- first list, first item
- first list, second item
- first list, third item

- second list, first item
- second list, second item
- second list, third item
```

### Expected

```html
<ul>
  <li>first list, first item</li>
  <li>first list, second item</li>
  <li>first list, third item</li>
</ul>
<ul>
  <li>second list, first item</li>
  <li>second list, second item</li>
  <li>second list, third item</li>
</ul>
```

### Actual

```html
<ul>
  <li>first list, first item</li>
  <li>first list, second item</li>
  <li>
    <p>first list, third item</p>
  </li>
  <li>second list, first item</li>
  <li>second list, second item</li>
  <li>second list, third item</li>
</ul>
```

**Comment by winniehell** [comment]
@gettalong I am not sure if I misunderstand what is going on here. In my opinion, the empty line should separate the two lists like in the following examples:

```
$ kramdown
* kram
+ down
- now

1. kram
2. down
3. now
```

```html
<ul>
  <li>kram</li>
  <li>down</li>
  <li>now</li>
</ul>

<ol>
  <li>kram</li>
  <li>down</li>
  <li>now</li>
</ol>
```

```
$ kramdown
* kram
+ down
- now
1. kram
2. down
3. now
```

```html
<ul>
  <li>kram</li>
  <li>down</li>
  <li>now
    <ol>
      <li>kram</li>
      <li>down</li>
      <li>now</li>
    </ol>
  </li>
</ul>
```

**Comment by gettalong** [comment]
Blank lines cannot be used to separate lists of the same type - see https://kramdown.gettalong.org/syntax.html#lists. In fact, blank lines between list items are used to determine whether to wrap a simple list item into a paragraph or not (is described in the mentioned link).

To separate two block level elements using an EOB marker (`^`).

As for your other two examples:

* The first contains an unordered followed by an ordered list, so there are clearly two separate list.

* In the second example, since there is no blank line, lazy indentation comes into play. The parser encounters an unordered list in the first three lines. Then something that doesn't start an unordered list item is found and put into the content of the last list item. Depending on whether you are using pure kramdown or GFM mode, you either get a paragraph with just text or a nested ordered list.

**Comment by winniehell** [comment]
@gettalong Sorry for not catching the example in the syntax definition which exactly covers this case. :disappointed:

... and thank you for quick reply and good explanation! :heart:

**Comment by gettalong** [comment]
@winniehell No problem :smile:
