### ISSUE TITLE
Space between initial HTML tag and text not getting stripped from Header ID

### ISSUE THREAD

**Issue by peckjon** [gettalong/kramdown#412]
Created a page containing the markdown:
`#### <i class="fa fa-globe"></i> Internet Access`

The space between the `<i>` tag and the text was not stripped from the ID in generated HTML:
`<h4 id="-internet-access">`

Expected:
`<h4 id="internet-access">`

**Comment by gettalong** [comment]
If you use the kramdown parser, you will get the result that you expect. If you use the GFM parser, you get what GFM expects, see https://github.com/gettalong/kramdown/wiki/GFM-test-case#-internet-access

So this is not a bug in the case of GFM but the (reverse engineered) intended way.

**Comment by peckjon** [comment]
Please re-open.  HTML Compatibility requires that ID should [start with a letter](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).  Regardless of parser, the generated ID should never start with a hyphen.

**Comment by gettalong** [comment]
@peckjon The purpose of the GFM parser is to be compatible with Github Flavoured Markdown. So if they do it like that (even if it makes no sense or breaks compatibility), the GFM parser should do it, otherwise it is a "bug" (I had already one case where we had to adjust the parser to include flaws so that it mimics GFM better).

What do you mean by "appropriate project"?

**Comment by peckjon** [comment]
I understand now -- thanks for clarifying.  Time for me to go pester GitHub I guess (that'll go well!)
