### ISSUE TITLE
Support of footnotes in image caption (latex output)

### ISSUE THREAD

**Issue by michaelfranzl** [gettalong/kramdown#423]
It would be handy if the following would be supported:

    ![caption[^1000]](image.jpg)
    
    [^1000]: Footnote

Right now, kramdown outputs latex:

    ![caption\footnote{Footnote}](image.jpg)

Ideally, it should ouput:

    \begin{figure}
    \begin{center}
    \includegraphics{image.jpg}
    \end{center}
    \caption{caption\footnote{Footnote}}
    \end{figure}

**Comment by gettalong** [comment]
@michaelfranzl The thing is that for images the part in brackets is the alternative text which cannot contain any elements since it is just text.

However, even if we remove the exclamation mark to turn it into a normal link, it doesn't work:

~~~
<p>[caption<sup id="fnref:1000"><a href="#fn:1000" class="footnote">1</a></sup>](image.jpg)</p>

<div class="footnotes">
  <ol>
    <li id="fn:1000">
      <p>Footnote <a href="#fnref:1000" class="reversefootnote">&#8617;</a></p>
    </li>
  </ol>
</div>
~~~

So that's a bug.

**Comment by gettalong** [comment]
Hmm... after a bit more checking I found the problem (a problem with the `LINK_BRACKET_STOP_RE` regexp not taking footnote markers into account).

*However*, if I would fix it, the resulting HTML wouldn't be conforming to HTML5 anymore since [`<a>` tags may not be nested](http://w3c.github.io/html/single-page.html#the-a-element).

So I guess the best thing to do is to leave it be and document this restriction in the syntax documentation. @michaelfranzl What do you think?

**Comment by michaelfranzl** [comment]
Yes, just documenting the restriction would help.

**Comment by gettalong** [comment]
Thanks for your response!

Since kramdown is mainly designed for markup-to-HTML conversion, other output formats that are more flexible only come second in some regards, as in this case. Which is a bummer... sorry for that.
