### ISSUE TITLE
Cannot invoke to_hash_ast on a KramDown::Document instance

### ISSUE THREAD

**Issue by 5t111111** [gettalong/kramdown#435]
To convert `Kramdown::Document` to other formats, you can invoke implicitly defined methods (`to_*`) via `method_missing` implementation.

However, invoking `to_hash_ast` fails as `hash_ast` is camelize to `HashAst` under the hood, but there defines a class `HashAST`. 

I think there are some possible solutions, but I am still not sure what is the best way to solve it:

- Rename `HashAST` class to `HashAst`, but obviously it causes a breaking change
- Define `to_hash_ast` explicitly, but it lacks consistency and DRY implmentation
- Modify `Kramdown::Utils.camelize`to support `HasAST`, but, umm it looks not good

I will consider to send a pull request If there's a solution you prefer.

**Comment by gettalong** [comment]
Thanks for opening the issue but the standard solution is to create the converter yourself and use it: `Kramdown::Converter::HashAST.convert(@doc.root, @doc.options)`. The `#to_*` method are only there for convenience and were originally implemented so that kramdown provides the same interface as other libraries.

**Comment by 5t111111** [comment]
@gettalong It is really appreciated, thanks!
