### ISSUE TITLE
generate pdf throw an exception

### ISSUE THREAD

**Issue by yangjianyi** [gettalong/kramdown#438]
when i use `Kramdown::Document.new(content, input: 'markdown').to_pdf` to generate pdf 
it throws an exception

```
Your document includes text that's not compatible with the Windows-1252 character set.
If you need full UTF-8 support, use TTF fonts instead of PDF's built-in fonts.
```

**Comment by gettalong** [comment]
This is an error message from Prawn, the PDF library that kramdown uses to generate PDFs. The PDF converter class of kramdown is very basic and meant to be subclassed to output a proper PDF. Then you can register TrueType fonts (TTF fonts) so that the Unicode characters you are using are displayed correctly.
