### ISSUE TITLE
Everything is automatically wrapped with <p> tag

### ISSUE THREAD

**Issue by denysmedynskyi** [gettalong/kramdown#446]
Code example:
```
[19] pry(main)> Kramdown::Document.new('abc').to_html
=> "<p>abc</p>\n"
```
Expected result
```
[19] pry(main)> Kramdown::Document.new('abc').to_html
=> "abc\n"
```
Is is possible to pass some option?

**Comment by gettalong** [comment]
This is just a markup converter's function: Take some input in plain text and convert it to a certain output format, in this case HTML..

So the result you are getting is the correct one since your input describes a paragraph in kramdown's markup format. If you don't want the input converted to HTML, don't use kramdown for it.
