### ISSUE TITLE
Rendering html_element not supported for PDF converter

### ISSUE THREAD

**Issue by fidalgo** [gettalong/kramdown#449]
kramdown version: 1.13.2
prawn (2.2.2)
prawn-table (0.2.2)

HTML file
```
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<p></p>
</body>
</html>
```

`kramdown index.html -o pdf`

output:
`Warning: Rendering html_element not supported for PDF converter (line 2)`

I've tried a more complex files and they fail, so I've tried this very simple file.

Am I missing something?

**Comment by gettalong** [comment]
If you wanna parse HTML with kramdown, you have to tell kramdown to do so, e.g. by using `-i html`.

However, the error message you are receiving is quite explicit: Rendering general HTML elements is just not supported.

I recommend using the options `-i html -o kramdown` to see whether any HTML elements are still in the output, and then adjusting the input sothat those are left out.

Changing your example to:

~~~ html
<p>This is <b>a test</b></p>
~~~

And running `kramdown -i html -o kramdown` yields the following:

~~~
This is **a test**
~~~

Since there are no HTML elements, using `-o pdf` **will** create a PDF file from the input.
