### ISSUE TITLE
Warning: this should not occur - no block parser handled the line

### ISSUE THREAD

**Issue by pathawks** [gettalong/kramdown#473]
We are using kramdown as a SmartyPants processor. We only want kramdown to convert punctuation, we don't need any MarkDown. We do not want the output wrapped in a `<p>` tag, but we do want any HTML tags to be passed through, rather than escaped.

https://github.com/jekyll/jekyll/blob/621df9db8e72cfa9706ccd52b86a590bcd5d7cc3/lib/jekyll/converters/smartypants.rb#L3-L9

The problem is, we are seeing this warning message every time the parser is called:
https://github.com/gettalong/kramdown/blob/a8375683c2873d09a24be53594056199725e068e/lib/kramdown/parser/kramdown.rb#L153

It is expected that no block processor handled the line: we are using it completely inline.

Is there any way we can disable this warning, or is there something we are doing wrong when using kramdown for inline text?

**Comment by gettalong** [comment]
The kramdown parser expects each line to be handled by a block parser (i.e. there is no inline text mode where no block parsing is done). Since you are just using a single block parser (`:block_html`) lines that it doesn't match will generate this warning. This is expected and correct.

So in your case first think about what you want kramdown to do with such an unhandled line. Then write a new parser method that handles any line given (i.e. a catch all block parser) and add your logic. After that add the new block parser method as last item in the block parser's array. This will lead to correct behaviour and no warning message.

**Comment by pathawks** [comment]
Thank your for your response.

It seems that what I am trying to do is impossible without also subclassing the HTML converter and/or parser?
Even if I add the text to the AST as a paragraph with the `transparent: true` option, I still get this warning. If I do not include the `transparent: true`, it will output `<p>` tags, which is what I am trying to avoid.

**Comment by gettalong** [comment]
You already subclassed the parser ( https://github.com/jekyll/jekyll/blob/621df9db8e72cfa9706ccd52b86a590bcd5d7cc3/lib/jekyll/converters/smartypants.rb#L3-L9 ), so the scaffold is already there.

Try adding something like this to your `Kramdown::Parser::SmartyPants` class and add `:content` to the `@block_parsers` array (untested):

~~~ ruby
CONTENT_MATCH = /^.*?\n/
def parse_content
  add_text(@src.scan(CONTENT_MATCH), @tree)
end
define_parser(:content, /^/)
~~~

If you provide a minimum Ruby source file with which I can easily reproduce the problem, I can probably help you more.
