### ISSUE TITLE
Autolinking is not compatible with redcarpet and breaks GFM

### ISSUE THREAD

**Issue by abitrolly** [gettalong/kramdown#490]
[kramdown autolinking](https://kramdown.gettalong.org/syntax.html#automatic-links) feature is strange. The better name for it is `semiautolinks`, because you still need to decorate every URL manually. This is different from [Redcarpet](https://github.com/vmg/redcarpet) `:autolink` extension and GFM autolinking https://help.github.com/articles/autolinked-references-and-urls/

**Comment by gettalong** [comment]
Hmm... I don't really know what you want... kramdown's syntax is clearly defined by its syntax document. Redcarpet has a different syntax, so what? Each Markdown converter differs in some ways from most of the others. None is clearly better than the other (otherwise we would have a real Markdown standard).

If you like how redcarpet converts Markdown, please use Redcarpet. If you like how kramdown does its job, please use kramdown. But it is just a decision you have to make.

Aside from this, take a look at the [original Markdown spec](https://daringfireball.net/projects/markdown/syntax#autolink) by Gruber where you will find the reason why kramdown implements these autolinks.

Could you clarify what you want? And note that changes to kramdown's syntax have a very high chance of only being implemented in a new major version. Changes to kramdown's GFM parser are implemented if the current implementation doesn't match the GFM one and are considered bugs.

**Comment by abitrolly** [comment]
Current implementation of GFM parser in kramdown doesn't match GFM - https://help.github.com/articles/autolinked-references-and-urls/#urls

kramdown GFM doesn't link URLs in pages that are linked by GitHub in source GFM. See https://kubernetes.io/docs/reference/generated/kubectl/kubectl/ for example.

**Comment by gettalong** [comment]
Okay, then this has already been requested in #306 but there has not been a pull request for this. Since #306 is already tracked in the [Feature Requests Project](https://github.com/gettalong/kramdown/projects/1), I will close this issue.

**Comment by abitrolly** [comment]
Ok. So #306 is not actually closed.. https://github.com/gettalong/kramdown/projects/1

**Comment by gettalong** [comment]
It is closed because it is waiting for a pull request, as stated on the feature requests project page.

**Comment by abitrolly** [comment]
That is strange. Usually issues are closed when they are resolved. This one is not resolved.

**Comment by gettalong** [comment]
These issues are feature requests that need a pull request. So they are resolved from my point of view. And are therefore assigned to the feature requests project.

**Comment by abitrolly** [comment]
Fixing GFM rendering to match official GFM definition is a feature request?

**Comment by cup** [comment]
https://github.com/gettalong/kramdown/issues/306
https://github.com/gettalong/kramdown/issues/490
https://github.com/gettalong/kramdown/pull/528
