### ISSUE TITLE
Katex Math engine not working

### ISSUE THREAD

**Issue by rhazegh** [gettalong/kramdown#506]
In Rails console I do:

```
pry(main)> Katex::VERSION
=> "0.4.3"
pry(main)> Kramdown::VERSION
=> "1.16.2"
pry(main)> text = "The higher the ratio the better the performance. \n\n \\[Sharpe\\ ratio,\\ S_{h} = \\frac{R_{p} - r_{f}}{\\sigma_{P}}\\]"
=> "The higher the ratio the better the performance. \n\n \\[Sharpe\\ ratio,\\ S_{h} = \\frac{R_{p} - r_{f}}{\\sigma_{P}}\\]"
pry(main)> Kramdown::Document.new(text, {math_engine: 'katex', math_engine_opts: {}}).to_html
=> "<p>The higher the ratio the better the performance.</p>\n\n<p>[Sharpe\\ ratio,\\ S_{h} = \\frac{R_{p} - r_{f}}{\\sigma_{P}}]</p>\n"
```

It looks like math_engine has no effect. Am I doing anything wrong?

**Comment by gettalong** [comment]
Two things:

* You need to use the correct [math syntax](https://kramdown.gettalong.org/syntax.html#math-blocks) so that kramdown. I.e. use `$$` to delimit math blocks and inline math.

* Make sure that you have everything setup as written at the [math engine's documentation page](https://kramdown.gettalong.org/math_engine/katex.html).

**Comment by gettalong** [comment]
Ah, sorry, I just saw that the KaTeX math engine is the one not yet released, the information got published to the website in error. So with the next release the engine will work. Sorry about that!

**Comment by gettalong** [comment]
@rhazegh Next release will be today or in the coming days, then the KaTeX math engine will be available.

**Comment by rhazegh** [comment]
@gettalong Cool. Thank you for the update :) 👍
