### ISSUE TITLE
HTML tag with attribute value not enclosed in quotes is not processed

### ISSUE THREAD

**Issue by mojavelinux** [gettalong/kramdown#522]
In the HTML to native function, the parser is not recognizing (or processing) an HTML tag if it contains an attribute value that is not enclosed in quotes (e.g., `<img src="image.png" width=100>`. However, dropping the quotes around an attribute value is valid HTML.

Is this something you think Kramdown should permit? If so, I'd be happy to update the parser to support quote-less attributes.

**Comment by gettalong** [comment]
This is actually intended, see https://kramdown.gettalong.org/syntax.html#html-blocks - kramdown only supports the XHTML variant of HTML (with some easy to implement exceptions) to make things easier to parse.

I don't think that this is a major obstacle to using kramdown since people immediately see that the didn't follow the correct syntax and correct it.

I'm not opposed to making the HTML parser more complete but it shouldn't come with a high cost.

**Comment by mojavelinux** [comment]
Understood, though I think this can be done with very limited overhead by reusing the existing regular expressions. A reasonable trade-off is that we only consider values with only letters and numbers and no spaces. I'll submit a proposal for review.

**Comment by gettalong** [comment]
Thank you for your contribution!

**Comment by mojavelinux** [comment]
Thank you for reviewing and merging!
