### ISSUE TITLE
Ability to specify parser in document

### ISSUE THREAD

**Issue by tammersaleh** [gettalong/kramdown#535]
I'd like to be able to specify that a particular document is using the GFM parser (that document uses the triple-backtick fenced code blocks).  I tried `{::options input="GFM" /}` at the top of my document, but that resulted in `Unknown kramdown option 'input'`

Is there a way of doing this?  If not, is there a way of allowing the triple-backtick fenced code block syntax globally (without the rest of GFM)?

btw, I'm a huge fan of Kramdown (and a new backer)!

**Comment by gettalong** [comment]
The input format is not an option and can therefore not be specified as one. Furthermore, the input could also be 'HTML', and it doesn't make sense to specify the input format in the format itself because there is no general way to do that (e.g. how would you do this for HTML?).

As for changing the kramdown parser: I'm very reluctant to do so because the kramdown parser should not be configurable (to allow parsing any document in the same way irrespective of set options). The easiest way to achieve something what you want is to subclass the kramdown parser and adapt the fenced code block parsing method.

So if you use the kramdown parser instead of the GFM parser you need to use the standard triple tildes (which is understood by GFM as well).

Thanks for backing!

**Comment by gettalong** [comment]
@tammersaleh I will close this issue since I think there is nothing to do here. If I'm wrong please comment and I will re-open if necessary.
