### ISSUE TITLE
Special characters don't render well in math mode

### ISSUE THREAD

**Issue by louisabraham** [gettalong/kramdown#537]
I had issues with blocks like below.

    $#$

makes MathJax bug

    $``string"$

the backticks are interpreted as a code block.

Of course, this is solved by escaping, but it would be nice if the math blocks could automatically escape their content (pandoc does it).

**Comment by gettalong** [comment]
I don't really get the problem - might you have missed some parts because in the first block there is a hash `#` but not in the second one...

If I use the following as input for kramdown:

~~~
$$#$$
~~~

I get the following output:

~~~ html
<script type="math/tex; mode=display">#</script>
~~~

which seems about right.

Could you be more specific regarding what you provide as input, the current output and what you would expect?

**Comment by louisabraham** [comment]
Oh, my bad. I got my mistake some hours ago and forgot to close this issue. I used simple dollars instead of double (because of pandoc)...
