### ISSUE TITLE
Indented link references after list cause "loose" list item

### ISSUE THREAD

**Issue by dgw** [gettalong/kramdown#584]
The following Markdown snippet results in the last list item being wrapped in `<p>` tags:

```markdown
* Config options can be set/overridden via environment variables [[#1096][]]
* Example service unit files now include a multi-instance template for systemd
  [[#1059][]]

  [#1059]: https://github.com/sopel-irc/sopel/pull/1059
  [#1096]: https://github.com/sopel-irc/sopel/pull/1096
```

Output:

```html
<ul>
  <li>Config options can be set/overridden via environment variables [<a href="https://github.com/sopel-irc/sopel/pull/1096">#1096</a>]</li>
  <li>
    <p>Example service unit files now include a multi-instance template for systemd
[<a href="https://github.com/sopel-irc/sopel/pull/1059">#1059</a>]</p>

  </li>
</ul>
```

Removing the spaces before the link references eliminates the extra HTML:

```markdown
* Config options can be set/overridden via environment variables [[#1096][]]
* Example service unit files now include a multi-instance template for systemd
  [[#1059][]]

[#1059]: https://github.com/sopel-irc/sopel/pull/1059
[#1096]: https://github.com/sopel-irc/sopel/pull/1096
```

Output:

```html
<ul>
  <li>Config options can be set/overridden via environment variables [<a href="https://github.com/sopel-irc/sopel/pull/1096">#1096</a>]</li>
  <li>Example service unit files now include a multi-instance template for systemd
[<a href="https://github.com/sopel-irc/sopel/pull/1059">#1059</a>]</li>
</ul>
```

Reading the [Markdown link syntax](https://daringfireball.net/projects/markdown/syntax#link) on Daring Fireball, the start of a link reference definition is "Square brackets containing the link identifier (optionally indented from the left margin using up to three spaces)". I think that optional indent should be used for visual effect in the raw/edit view, and ignored during rendering. As a Markdown author, I don't expect it to affect anything visible.

Observed on 1.17.0 (under Jekyll), but I don't see any changes in 2.x that suggest this was changed at all recently.

**Comment by gettalong** [comment]
This is the intended behaviour, as per the [kramdown specification](https://kramdown.gettalong.org/syntax.html) (please note that any other specification doesn't apply to the kramdown syntax).

The reason: If you are inside a list, kramdown stores the indentation for the current list item. In your example, that would be two characters. If the following lines have at least this much indentation, they are considered part of the list item. This allows you to use any of the block elements inside a list item.
Furthermore, kramdown has to decide whether a list item with only text should be wrapped within a paragraph or not. This is determined by checking whether the text is followed by a blank line. In your example, the text of the first list item is not followed by a blank line, but the text of the second item is. And that blank lines belongs to the list item because the following lines are also indented.

**Comment by dgw** [comment]
Regarding the applicability of "any other specification", the kramdown specification says essentially the same thing, FWIW: "The link identifier in square brackets, optionally indented up to three spaces".

Does it really make sense for the renderer to base its rendering behavior on the indentation level of an element that will be dropped from the output? Obviously I can work around this by changing the number of spaces used for indenting the links, but still.

**Comment by gettalong** [comment]
Yes, that is correct regarding the three spaces. But you have to take indented block elements into account. One or the other has to has preference, and for kramdown the indented block elements come first.

Just have a look at the order of the elements: If above a line a block element with indentation has started, the amount of indentation for this element doesn't count to the "three spaces" rule.
