### ISSUE TITLE
No way to add a table caption

### ISSUE THREAD

**Issue by Carpetsmoker** [gettalong/kramdown#593]
The Kramdown syntax currently offers no way to add a [caption element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption).

Is this a feature that could be added to Kramdown? I can look at implementing it if a syntax can be agreed on.

The only other Markdown implementation I can find which supports this is [Pandoc](http://pandoc.org/MANUAL.html#tables), which adds `Table: the caption` after the actual table:

    | Header  | w00t   |
    | :-----  | -----: |
    | Value   | 18 251 |
    | Another | 7 254  |

    Table: The caption

This seems reasonable enough to be, and sticking with it makes sense. But can also do something else; I have no strong opinions.

**Comment by Carpetsmoker** [comment]
BTW, my current solution is to add `_plugins/caption.rb` (using Jekyll) with:

    class Jekyll::MarkdownCaption < Jekyll::Converters::Markdown
      def convert(content)
          super
            .gsub(/<\/table>\n+<p>Table: (.*?)<\/p>/, '<caption>\1</caption></table>')
      end
    end

Which is rather ugly, but works for the time being and allows me to continue writing my document as I want it :-)

**Comment by gettalong** [comment]
The table syntax is only meant for really simple tables.

If you need more than the simple table syntax provides, it would probably be better to either use HTML or something like your custom solution. Another way would be to adapt the HTML converter for your specific use case, i.e. if a table is followed by a paragraph starting with "Table:", convert that paragraph into a `<caption>` element instead of a `<p>` element.
