### ISSUE TITLE
MathJax v3 no longer processes Kramdown's math engine's <script type="math/text" /> tags

### ISSUE THREAD

**Issue by abevoelker** [gettalong/kramdown#626]
Just a heads-up for your [MathJax support](https://kramdown.gettalong.org/math_engine/mathjax.html), I tried to add some math to my Jekyll + Kramdown blog, and couldn't figure out why MathJax wasn't rendering Kramdown's emitted `<script type="math/tex">` tags.

Turns out MathJax [released v3.0.0](https://github.com/mathjax/MathJax/releases/tag/3.0.0) a couple weeks ago, and all their "getting started" / installation docs are now pointing to this newer version, which I dutifully followed so am using on my site. It further turns out this version doesn't render the "math/tex" script tags, quietly mentioned in the last bullet point in the [upgrading from v2 to v3 docs here](http://docs.mathjax.org/en/latest/upgrading/v2.html#changes-in-the-mathjax-api).

That bullet point as well as [this example](https://github.com/mathjax/MathJax-demos-web/blob/dfb21d861c13d9e9bcf8b2ad17997973538bdf3c/v2-script-tags.md) in their demos repo provide a configuration snippet that can be slightly modified to make MathJax v3 load Kramdown's `<script type="math/tex">` tags:

```javascript
<script>
  MathJax = {
    options: {
      renderActions: {
        find: [10, function (doc) {
          for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
            const display = !!node.type.match(/; *mode=display/);
            const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
            const text = document.createTextNode('');
            node.parentNode.replaceChild(text, node);
            math.start = {node: text, delim: '', n: 0};
            math.end = {node: text, delim: '', n: 0};
            doc.math.push(math);
          }
        }, '']
      }
    }
  };
</script>
```
(note I had to replace the "text/tex" in their snippet with "math/tex")

With that configuration snippet MathJax v3 is now working with Kramdown.

**Comment by gettalong** [comment]
@abevoelker Thanks and sorry for the long delay regarding an answer!

So, would it be better to change the output to use  `\(...\)` for inline and `\[..\]` for displayed math? Since that was supported in v2 and is still the default in v3, there should be no problem regarding backwards-compatibility.

Any thoughts?

**Comment by abevoelker** [comment]
No problem. Regarding your question, I don't know to be honest as I'm new to MathJax! :upside_down_face: Sorry I can't be of more help.

**Comment by gettalong** [comment]
I changed the output to use the standard syntax since this works in v2 and v3. The only thing that will not work is using the MathJax preview option since that is not available anymore in v3 (and wouldn't work with the chosen output syntax anyway). However, I don't think that this is a huge problem.
