### ISSUE TITLE
TOC with external links

### ISSUE THREAD

**Issue by alexanderbock** [gettalong/kramdown#659]
It would be nice to have a feature along the lines of `{.toc-entry # [External](www.example.org)} `which would insert an external link into the generated toc (either autogenerated or using {:toc}.

Example:
```
# First heading
## First subheading
{.toc-entry # [External Links](www.example.org)} 
{.toc-entry ## [GH](www.github.com)}
# Second heading
```

Would result in:

1. First heading
  a. First subheading
1. [External Links](www.example.org)
  a. [GH](www.github.com)
1. Second heading

Without the "External Links" or "GH" sections actually showing up in the floating text

**Comment by gettalong** [comment]
I don't think that this would be a good fit for kramdown itself. The TOC is a table of contents for the page, not a general menu. So every entry should be a link to something on the page.

If you want to do this, I recommend adapting the HTML converter class so that certain headers will appear in the TOC but not on the page.
