### ISSUE TITLE
Slightly richer interface for querying and changing document.

### ISSUE THREAD

**Issue by ioquatix** [gettalong/kramdown#661]
Thanks for your work on this gem.

I want to read a `README.md` file and replace the usage section with a dynamically generated one.

```ruby
	if readme_path = @base.path_for('README.md')
		@document = Kramdown::Document.new(File.read(readme_path), syntax_highlighter: nil)
		
		if title = @document.root.children.shift
			@title = title.children.first.value
		end
		
		start = @document.root.children.index{|node| node.children.first&.value == "Usage"}
		finish = start + 1
		
		while node = @document.root.children[finish]
			if node.type == :header
				break
			else
				finish += 1
			end
		end
		
		@document.root.children[start...finish] = [
			Kramdown::Element.new(:raw, "<content:usage/>")
		]
	end
```

This is the implementation I came up with and it works.

I'm wondering if we should do something to make this a little bit more ergonomic/reliable?

Some issues that stick out to me:

- Find a section with a given title.
- Remove and replace that section with something else.

Maybe the `Element` class should have some easier way to access the text of all children combined (e..g `node.children.first&.value` seems a bit hacky).

It would be nice to consider a document as a series of sections with titles, or at least present that illusion so replacing sections would be eaiser.

```ruby
section = document.sections("Usage")
section.replace(
	Kramdown::Element.new(:raw, "<content:usage/>")
)
```

If this is beyond the scope of this gem, please feel free to close, however I'm happy to discuss further if you think there is merit to this idea.

**Comment by ioquatix** [comment]
One more query I'd like to be able to do more easily, is to get the first line and or first paragraph (as lines) from the document. Ideally, some easy way to get one or more paragraphs, and perhaps grouped by titles, e.g. 

```ruby
document.section(named: 'Usage').paragraphs.first.lines.first
```

**Comment by gettalong** [comment]
This is a nice idea but I don't know if it fits well into the `Kramdown::Element` class. The class is meant as node/container for the abstract syntax tree. Operations on the elements should be done by a separate class, like the converters.

The query syntax kinda looks a bit like JQuery or XPath for kramdown :wink: Alas, after a quick look at the REXML XPath parser I don't think that we could re-use it for this purpose.

Your code for finding the section might work in case only headers with the same level are used. Otherwise you might only return part of the section, i.e.

~~~ markdown
# Usage

bla bla bla

## Subsection of Usage

ble ble ble

## Another Subsection

bli bli bli

# New Section
~~~

So the header level should probably be taken into account since kramdown itself has no notion of a section.

Other thoughts:

* What would `document.section` return? Or `Section#paragraphs`? This kinda looks like another tree structure to me.

* What if a section doesn't contain a paragraph but only, for example, a code block?

* Should `#paragraphs` also return paragraphs in sub-elements, i.e. in block elements of the section like blockquotes or lists?

And if we are at this point, the complexity of it probably merits a separate library.

Another thought: Maybe what you want to do is easier if you walk the whole AST with a kind of event-based parser (similar to how SAX works for XML) and extract the things you need (like element positions, text, ...)?

**Comment by ioquatix** [comment]
I'm in agreement with all your points.

I don't really want to write a streaming parser, but I already did that in the past: https://github.com/ioquatix/trenni-markdown but this one is really only for a PoC and not in any way shape or form production ready. I thought about using it for this job, but I quickly decided against it.

I'd be happy for this to exist outside of the `Kramdown::Element` class. To me, that's a fairly reasonable choice. However, to keep things easy, maybe adding an entry point on the `Kramdown::Document` would make sense, e.g. `#query` or `#lookup` or the previously proposed `#sections`/`#paragraphs`.

I thought about one other solution. I could create my own `Converter` which only gets the first paragraph or title or whatever. However, I don't believe it could remove nodes. However, at the very least it would let me encapsulate the logic of getting the first paragraph / title into a robust class that fits with the existing implementation. Other than that, adding a query interface brings a lot of questions and decisions, so might not be the right direction in terms of keeping the library simple.

So, I think the way forward is either:

1. A custom converter for extracting the title (deleting it from the original document) and a 2nd converter to extract the first paragraph (ignoring code, lists, etc), or
2. A straight forward interface for navigating the document structure, and extracting parts of it.

Option 1 seems straight forward if you can confirm it should be possible for the converter to mutate the original document AST.

Option 2 seems like a nice addition, provided we implement it as a set of optional classes. For document manipulations, we need to be careful since it will invalidate the nodes. Maybe a simpler way is simply to disable or hide an element, so it's not rendered. That would let me extract the title without changing the syntax tree. However this still poses a problem when adding elements. The solution to this is not so elegant in Ruby: to use a linked list.

**Comment by gettalong** [comment]
If you go the converter way, you can do to the AST anything you like. Just make sure that you nest elements correctly. E.g. don't add `li` elements to a `p` element etc.

You also *can* use two converters but it would certainly be doable in one.

I'd propose that you take option 1 and see how it goes. If you think the implementation could be generalized in a useful way, we think about option 2.

**Comment by ioquatix** [comment]
Thanks for your help.
