### ISSUE TITLE
Parser selection seems unnecessarily complex

### ISSUE THREAD

**Issue by ioquatix** [gettalong/kramdown#664]
https://github.com/gettalong/kramdown/blob/ef22876f1273ef35fa6c31b22ce51f679be03380/lib/kramdown/document.rb#L99

I want to write:

```ruby
Kramdown::Document.new(source, parser: MyParser.new)
```

Or even better:

```ruby
MyParser.new.parse(source) => document instance
```

**Comment by ioquatix** [comment]
My advice would be, take the existing logic and put it into a method like:

```ruby
Kramdown::Document.parse(source)

def self.parse
  # current behaviour of Document.new
end
```

The document class should not do parsing

```ruby
Kramdown::Document.new(root, options)
```

**Comment by gettalong** [comment]
Yeah, the initialization was done in a similar way to how existing libraries at the time did it to make changing to kramdown easier.

Since this is the main entry point used by just about any app/library that uses kramdown, I won't change it for compatibility reasons.

You can already do `root, warnings = Kramdown::Parser::Kramdown.parse(source, options)` for parsing with a certain parser. And `output, warnings = Kramdown::Converter::Html.convert(root, options)` for converting the AST.

The `Kramdown::Document` class is just there as an easy entry point to parsers/converters.
