### ISSUE TITLE
Render footnotes inside span tag

### ISSUE THREAD

**Issue by filipemosca** [gettalong/kramdown#670]
Hi! I have a blog with jekyll and I use footnotes in every blog post to cite references. But the footnotes are rendered inside `<div class="footnotes">` tags and this tag is not read for some feed readers and page readers. 

For example, Firefox reader view doesn't render the footnotes section. I think this is caused because of the `<div>` tag instead of a `<p>` or `<span>` tag. So I tested changing a single footnotes html, putting them inside a `<span>` tag and the Firefox reader view work fine rendering all the page.

And some webpage to ebook converters don't detect the footnotes section too.

Is it possible to render footnotes section inside a `<span>` or `<p>` tag instead of `<div>` tag?

Thanks for the attention and sorry for the bad english (I am not a native speaker)

**Comment by gettalong** [comment]
If you need to use `<span>` instead of `<div>`, the best option for you would be to create a sub-class of the HTML converter that overrides the footnote generation code.

The `<div>` tag is used to structure block content (like `<p>`) whereas a `<span>` is used for inline content (like `<em>`). So generally using the latter is no option here.
