### ISSUE TITLE
Abbreviations should not be replaced within embedded SVGs

### ISSUE THREAD

**Issue by KasparEtter** [gettalong/kramdown#671]
```md
<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20">This TEST fails.</text>
</svg>

*[TEST]: This Escapes SVG Text.
```

results in

```html
<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20">This <abbr title="This Escapes SVG Text.">TEST</abbr> fails.</text>
</svg>
```

However, `<abbr>` is not valid within SVG and, as a consequence, the text within it is no longer rendered. I really like the [abbreviations](https://kramdown.gettalong.org/syntax.html#abbreviations) feature but I wonder: Is there a way to opt out of the replacement for part of the document?

In particular, `markdown="0"` does not work even though [the documentation](https://kramdown.gettalong.org/syntax.html#html-blocks) suggests so:
> If an HTML tag has an attribute `markdown="0"`, then the tag is parsed as raw HTML block.

Escaping the embedded SVG with `{::comment}` and `{:/comment}` also doesn't work as kramdown outputs the part within this as an HTML comment, which is then ignored by the browser.

I also tried to trick the replacement engine, for example, with [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) around the abbreviation but also to no avail.

I think the best fix would be to ignore all text within `<svg>` (or even any HTML tag) when wrapping abbreviations with `<abbr>`. However, in my case I'm looking for an approach that works in kramdown 1.17.0 as I'm using [GitHub Pages](https://pages.github.com/versions/). I'm not familiar with Ruby so I want to ask you as the author: Can you think of any other "hack" to prevent abbreviation replacements within embedded SVGs?

The only one (and thus the best) I found so far is to transform the case of the text with CSS (`text-transform: uppercase`). Using Bootstrap with its [utility classes](https://getbootstrap.com/docs/4.0/utilities/text/#text-transform), I can write my embedded SVG as:

```html
<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg" markdown="0">
    <text x="20" y="20">This <tspan class="text-uppercase">test</tspan> now works!</text>
</svg>
```

**Comment by gettalong** [comment]
Thank you for reporting this!

This is a bug because, as you noted, kramdown should leave raw HTML/XML tags alone. I have fixed this for the next version but if you depend on 1.17 you need to do the modification yourself. For this, change the line https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/kramdown/abbreviation.rb#L49 to `if child.type == :text && el.options[:content_model] != :raw`.

With this fix in place the following file

~~~ markdown
This is <em>some TEST</em> to check.

<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20">This TEST fails.</text>
</svg>
<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20" markdown="span">This TEST fails.</text>
</svg>

*[TEST]: This Escapes SVG Text.
~~~

gets converted to 

~~~ html
<p>This is <em>some <abbr title="This Escapes SVG Text.">TEST</abbr></em> to check.</p>

<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20">This TEST fails.</text>
</svg>
<svg width="100" height="30" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="20">This <abbr title="This Escapes SVG Text.">TEST</abbr> fails.</text>
</svg>
~~~

**Comment by KasparEtter** [comment]
Thank you for addressing this issue! Can you quickly elaborate on how you fixed this bug? Personally, I want to enable abbreviations in certain tags, such as `<details>` and `<figcaption>`, where I have Markdown processing enabled with `markdown="block"` or `markdown="span"`. Will this still be possible with your fix? I would have no problem setting `markdown="0"` on my SVGs. Given the `!= :raw` of your suggestion, I think/hope this is what you opted for.

**Comment by gettalong** [comment]
The fix is exactly the one I wrote in https://github.com/gettalong/kramdown/issues/671#issuecomment-755379639. And as can be seen by the example, the answer to your second question is "yes", this is possible.
