### ISSUE TITLE
Conflict with kramdown-man's Kramdown::Converter::Man class

### ISSUE THREAD

**Issue by postmodern** [gettalong/kramdown#675]
Hello and thanks for this gem. I noticed that a while ago [kramdown-man](https://github.com/postmodern/kramdown-man) started generating oddly formatted man pages. Appears that kramdown added it's own [kramdown/converter/man](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/man.rb) file and class which is shadowing kramdown-man's. This raises the question, what is the best way to override the built-in converters? Should I define my own `to_man` method in `Kramdown::Document` similar to what the `method_missing` method does, or open the converter class and override the `#convert`/`#convert_*` methods?

**Comment by gettalong** [comment]
I guess it depends on how similar/different your implementation is to the one included in kramdown. If the differences are small, overriding the `#convert_*` methods in the class would probably be the best option. Otherwise, loading your implementation file before the built-in one should invalidate the autoload directives that are used to load the files. So then only your implementation should be loaded.

**Comment by postmodern** [comment]
Appears that bundler is somehow always loading kramdown's `kramdown/convert/man.rb` file before my own. I'd probably have to rename the file to avoid conflicts. Considering renaming the converter class to just `Roff` since I avoided using groff directives to support BSD's nroff.

**Comment by gettalong** [comment]
Hm, strange regarding the loading. Maybe using `require_relative` here https://github.com/postmodern/kramdown-man/blob/master/lib/kramdown/man.rb#L3 does the trick?

**Comment by postmodern** [comment]
Ah clever. Had to add an ugly `require_relative '../../../lib/kramdown/converter/man'` to get the specs passing, but this shall do for a workaround.

**Comment by gettalong** [comment]
Glad it worked!
