### ISSUE TITLE
Link definitions erroneously assumed when using brackets in fenced blocks

### ISSUE THREAD

**Issue by koitsu** [gettalong/kramdown#676]
# Problem

kramdown believes some of my text in fenced blocks are trying to use link definitions.  The problem seems to happens when there are a **pair** of `[Foo]` texts spread across multiple lines.  If there is only a single `[Foo]` text (i.e. no matching pair), kramdown generates proper HTML for it, and there is no warning.

The workaround it to escape the brackets (ex. `\[Foo\]`).  And while that is (partially) acceptable, the -- I don't know what word to use; inconsistency? -- in behaviour is a bit odd.

If there's a way to temporarily disable this (via `{::option ... /}` or some other means), I'd love to know how.  This situation sort of reminds me of the importance of `<![CDATA[ ... ]]>` in SGML/XML.

NOTE: In the below example/results, please turn underscores into backticks.  I don't know how to get GitHub's Markdown parser to behave.  :(

# Versions

* kramdown 2.3.0
* Ruby 2.7.1p83

# Example

```
___
[Engine.Engine]
Foo=Bar
Blat=0

[SystemSettings]
Grok=false
___

Blah blah blah.

___
[Something.Else]
No=0

[Lalala]
Yes=1
___

___
[This.One.Will.Work]
IDontWantToKnow=true
___
```

# Result

```
bash-5.0$ kramdown -i markdown test.md
<p>___
[Engine.Engine]
Foo=Bar
Blat=0</p>

<p>[SystemSettings]
Grok=false
___</p>

<p>Blah blah blah.</p>

<p>___
[Something.Else]
No=0</p>

<p>[Lalala]
Yes=1
___</p>

<p><code>
[This.One.Will.Work]
IDontWantToKnow=true
</code></p>
Warning: No link definition for link ID 'engine.engine' found on line 2
Warning: No link definition for link ID 'systemsettings' found on line 6
Warning: No link definition for link ID 'something.else' found on line 13
Warning: No link definition for link ID 'lalala' found on line 16
```

**Comment by gettalong** [comment]
The "Markdown" parser doesn't support fenced codeblocks. This is the reason why the code blocks are turned into paragraphs. You would need to use the standard kramdown parser for code blocks with tildes to work:

~~~~~
~~~
[Engine.Engine]
...
...
~~~
~~~~~

If you want to use backticks instead of tildes, you need to use the GFM parser available through the `kramdown-parser-gfm` gem.

Btw. in most implementations of fenced codeblocks you can just use more than three characters if you want to include a literal fenced code block. I.e. start/end the code block itself with eg. 5 tildes and the literal codeblock with three tildes. Works for Github.

**Comment by koitsu** [comment]
My concerns did not have anything to do with paragraphs or `<p></p>` tags, but more with the warnings.  My concerns were:

1. Why kramdown treats things like `[Engine.Engine]` as link identifiers when there are no such reference link defined.  Quoting [kramdown's own documentation](https://kramdown.gettalong.org/syntax.html#reference-links), emphasis mine:

> If you don’t specify a link identifier (i.e. only use empty square brackets) or completely omit the second pair of square brackets, the link text is converted to a valid link identifier by removing all invalid characters and inserting spaces for line breaks. **If there is a link definition found for the link identifier, a link will be created. Otherwise the text is not converted to a link.**

I don't know how kramdown's parser works, but I assumed it was multi-pass, where it would look for things like link definitions (i.e. `[foo]: http://website.com/ "Some Text"`) in the first pass, then expand those when encountering `[foo]` in a subsequent pass (while leaving things like `[bar]` alone and without warning).  I now think this was a bad assumption on my part.

2. Why the issue described in #1 only happens for `[Engine.Engine]`, `[SystemSettings]`, `[Something.Else]`, and `[Lalala]` but not `[This.One.Will.Work]`.  In other words: the problem seems to be induced by "pairs" of `[foo]` strings, and that makes me think there may be a parser issue.  Along the same lines: note that `[This.One.Will.Work]` gets wrapped in `<code></code>` while the others don't.

If GH's parser is eating some of what I'm describing, here is the example file.  Try it yourself with `kramdown -i markdown foo.md`: https://pastebin.com/r5Z4tSgC

I'll add that if I use the combination of 5-tildes followed by 3-tildes, the #2 problem goes away, i.e. `Warning: No link definition for link ID 'this.one.will.work' found on line 26` is shown.  I would expect that warning to also be emitted when using backticks, but it strangely isn't.

P.S. -- Good thing I read the Email version of your reply, since the GH web UI parsed your 5-tildes.  :-)  Thanks for the tip!

**Comment by gettalong** [comment]
There are a few things at work here:

1. You convert the file using `kramdown -i markdown`. As I stated the markdown parser **does not support fenced codeblocks**. So for the parser any triple backticks are just that: backticks. So all your assumed codeblocks are one or more paragraphs. E.g. the first "codeblock" are actually two paragraphs because they are separated by a blank line.

2. When such a paragraph is parsed for span-level markup, the triple backticks are encountered. Since backticks can be used for inline code spans, the parser tries to match the three backticks to another set of three backticks. In the first four cases it won't find any because, as stated above, the first two "codeblocks" are actually four paragraphs. However, the last "codeblock" doesn't contain a blank line, so the backticks from the first and last line are matched and you get the `<code>` span.

3. You might not know but inline code spans can use more than one backtick. This is an escaping mechanism so that backticks can be used inside a code span.

4. When the bracketed items in the paragraph are encountered, kramdown looks for a matching link definition. If none is found, no error is thrown but a warning is generated to catch misspelled or missing link definitions.

5. The kramdown parser uses tildes for fenced codeblocks, not backticks. So if you want to use fenced codeblocks with the kramdown parser, you need to use tildes. If you want to use backticks, you have to use the [GFM parser](https://github.com/kramdown/parser-gfm).

ps. Github parsing the 5 tildes was expected and intended :)
