### ISSUE TITLE
issue when escaping code with angle-brackets that spans a new-line

### ISSUE THREAD

**Issue by bahamas10** [gettalong/kramdown#677]
I realize the title of this issue may seem overly verbose, but it appears that there is a very specific issue with tags not being escaped properly when inside backticks that span a newline.

### background

I recently switched my blog from jekyll 3 to 4, and as such switched from using `redcarpet` to `kramdown`.  For the most part, everything worked as expected (as far as I could tell).  I received an email from someone looking at a blog post of mine where it was clear the formatting had gotten completly broken, and rendered the bottom half of the post really awkward to read.

I looked into the markdown that was causing the issue and was able to distill it down to something very specific.

### the issue

I have a markdown file that looks like this:

``` md
an example command is `git clone
<repo>` where "repo" has angle brackets
around it and also begins a new line.
```

Notice the `git clone <repo>` line inside backticks - specifically how `<repo>` looks like an HTML tag and also starts a new line, even though it is contained inside backticks from the previous line.

Parsing this with a few parsers we can see that kramdown appears to handle this situation incorrectly:

#### rdiscount

```
$ cat html-in-code-tag-with-linkbreak.html | rdiscount 
<p>an example command is <code>git clone
&lt;repo&gt;</code> where "repo" has angle brackets
around it and also begins a new line.</p>
```

#### redcarpet

```
$ cat html-in-code-tag-with-linkbreak.html | redcarpet 
<p>an example command is <code>git clone
&lt;repo&gt;</code> where &quot;repo&quot; has angle brackets
around it and also begins a new line.</p>
```

#### kramdown

```
$ cat html-in-code-tag-with-linkbreak.html | kramdown 
<p>an example command is `git clone</p>
<repo>` where "repo" has angle brackets
around it and also begins a new line.
</repo>
Warning: Found no end tag for 'repo' on line 2 - auto-closing it
```

`redcarpet` and `rdiscount` correctly escape the angle brackets inside the backticks, whereas `kramdown` attempts to treat `<repo>` as an HTML tag.

---

Putting the angle brackets on the same line as the backticks start (not starting a line with `<repo>`) appears to fix this issue - using this file:

``` md
an example command is `git clone <repo>`
where "repo" has angle brackets
around it and DOES NOT begin a new line.
```

#### rdiscount

```
<p>an example command is <code>git clone &lt;repo&gt;</code>
where "repo" has angle brackets
around it and DOES NOT begin a new line.</p>
```

#### redcarpet

```
<p>an example command is <code>git clone &lt;repo&gt;</code>
where &quot;repo&quot; has angle brackets
around it and DOES NOT begin a new line.</p>
```

#### kramdown

```
<p>an example command is <code>git clone &lt;repo&gt;</code>
where “repo” has angle brackets
around it and DOES NOT begin a new line.</p>
```

---

### conclusion

I believe (without having looked through any of the source) this issue is caused by the line beginning with something that looks like HTML, even though it is contained inside backticks.  I was able to work around this in my blog by shuffling where i insert my line breaks (I try to maintain 80 columns in my own files).

**Comment by gettalong** [comment]
Thanks for reporting and yes, this might be a bug.

This has something to do with how kramdown tries to determine the end of a paragraph. If a block HTML or general XML tag is encountered, kramdown assumes that the paragraph has ended, eg.:

~~~
para line 1
para line 2
<repo>
xml tag contents
</repo>
~~~

~~~
<div markdown="1">
para line 1
</div>
~~~

So when the paragraph itself is parsed for span-level markup, only the first line of your example is included in the paragraph.

I will have to think about whether the current behaviour can be retained while making your example work.

**Comment by gettalong** [comment]
After having a more in-depth look at this:

* The example works in `rdiscount` and `redcarpet` not because of the backticks but because they handle HTML/XML tags differently. If you completely remove the backticks, you will find that the second line starts with `<repo>`. So the block parser of redcarpet/rdiscount ignores the XML/HTML tag. What's more is that if you remove the backticks the result is invalid because the angle brackets are not escaped.

* kramdown handles all HTML/XML tags to make sure that a syntactically valid output is generated, i.e. that correctly nested closing tags appear.

* The behaviour is different in kramdown and has its own quirks as you discovered. However, since kramdown can't know whether a certain custom HTML/XML tag name is a block or span level tag, it assumes that tags at the start of a line are block level tags. I thought about how I could change this to make your use case work but didn't come up with a solution. As you found you can just move that tag to the end of the last line to make everything work correctly.

So in this case kramdown "is working as expected".
