### ISSUE TITLE
Wrap Kramdown tables in a div

### ISSUE THREAD

**Issue by emaadmanzoor** [gettalong/kramdown#69]
I think it would be convenient to wrap kramdown-generated tables in a `div`.

Here's my use case:

I want to have a table with `width: 100%` and it's contents stretched to fill the full width (so I can't have a `display: block` on the table). But I also want an `overflow: auto` on the table, so if the screen is too narrow, the table scrolls horizontally.

The only way to do this is to have a wrapper `div` with `overflow: auto` set.

I've currently worked around it by setting `parse_block_html: true` and adding a `<div class="table-wrapper">` into my source markdown; you can see it in action [here](http://eyeshalfclosed.com/2013/08/04/beginning-how-to-prove-it/#question-2) and the source markdown [here](https://raw.github.com/emaadmanzoor/blog/gh-pages/_posts/2013-08-04-beginning-how-to-prove-it.md).

It would be neat to have this wrapper generated by kramdown, so the source markdown remains uncluttered.

**Comment by bric3** [comment]
Just a feedback, now this tweaks only works if there's blank lines before and after the markdown text. i.e. :

```
<div class="table-wrapper" markdown="block">

| some | table | here |

</div>
```

Not an expert on the topic.
Maybe there's this alternative : http://stackoverflow.com/questions/22291211/jekyll-how-to-get-markdown-parsing-inside-blocks-using-kramdown

**Comment by weibeld** [comment]
In kramdown v1.15.0 also works with only a blank line *after* the kramdown table:

```
<div markdown="block">
| some | table | here |

</div>
```

Output:

```
<div>
  <table>
    <tbody>
      <tr>
        <td>some</td>
        <td>table</td>
        <td>here</td>
      </tr>
    </tbody>
  </table>

</div>
```

However, this blank line after the kramdown table is necessary, otherwise the content of the div is not rendered by kramdown, and copied verbatim to the output.

**Comment by zabetak** [comment]
The suggestions proposed in the discussion so far look more like workarounds than a solution to the problem. If I have 100 markdown tables (and I want them to be scrollable) I have to add boilerplate code (`div` tags) everywhere. Moreover, if someone in the future adds another markdown table they need to remember to add the boilerplate code otherwise the table may not adapt well to the screen size.

Can't we have a configuration flag that allows to generate the wrapper div around tables on demand?
@gettalong It seems like a useful feature should we consider reopening this issue?

**Comment by gettalong** [comment]
@zabetak You wouldn't need to do it for every table, just adapt the HTML converter to your liking. Ie. add the `<div>` in the `#convert_table` method.

**Comment by zabetak** [comment]
@gettalong Thanks for the clarification. I am just discovering the Kramdown project (which is quite cool by the way :)) so apologies if I ask/suggest trivial things.

If I understand well you suggest to extend the HTML converter and override the behavior of `convert_table` method right? 

Just to complete the picture we are using Kramdown via Jekyll so to achieve what you suggest it appears to me that we should add custom Jekyll plugin and plug a custom subclass of HTML converter. Seems doable but it is a bit of overhead for something which appears a common use-case.

**Comment by gettalong** [comment]
@zabetak As I don't use Jekyll I can recommend the correct way of adding a custom converter or overriding the standard HTML converter. So please ask at Jekyll for how to do that.

The thing is: Everybody would like to have something like this in kramdown proper but it isn't the right place. There is a standard HTML converter that does its best to generate valid XHTML, without too much fuss. It is intentional that there aren't many knobs to customize the converter because checking all those knobs would slow things down from a performance standpoint, without much benefits for most people.

**Comment by zabetak** [comment]
@gettalong Undestood thanks for taking the time to comment on this!
