### ISSUE TITLE
Specifying a header ID that starts with a number is ignored

### ISSUE THREAD

**Issue by ArthurZey** [gettalong/kramdown#711]
Please forgive me if this is intended behavior, perhaps following a spec somewhere, but it seems that kramdown will autogenerate IDs that start with a number, but it will not respect manually specifying IDs. I don't see my usecase disclaimed under [Specifying a Header ID](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id).

## Autogeneration of ID for headings starting with numbers works
For example:
```
## 2021-03-30
```
yields
```
<h2 id="2021-03-30">2021-03-30</h2>
```
as expected. (The example remains true for header text that is purely numeric, such as `## 123`.)

(Although, I didn't understand how to reconcile that with the [HTML Converter](https://kramdown.gettalong.org/converter/html.html) documentation for "Automatic Generation of Header IDs", which suggested that I should expect a different result.)

## Specifying a custom header ID works for headings starting with `[a-z]`
And
```
## Foo
{: #bar}
```
and
```
## Foo {#bar}
```
both yield
```
<h2 id="bar">Foo</h2>
```
also as expected.

## Specifying a custom header ID starting with `[0-9]` does not work

So here's where I get the unexpected behavior:
```
## 2021-03-30: Foo {#2021-03-30}
```
yields
```
<h2 id="2021-03-30-foo-2021-03-30">2021-03-30: Foo {#2021-03-30}</h2>
```
and
```
## 2021-03-30: Foo
{: #2021-03-30}
```
yields
```
<h2 id="2021-03-30-foo">2021-03-30: Foo</h2>
```

Of course, I was expecting the following in both of the two examples immediately above:
```
<h2 id="2021-03-30">2021-03-30: Foo</h2>
```

I'm gathering that kramdown is ignoring manually specified header IDs when they start with numbers (since even adding `[a-z]` characters later in the ID doesn't help).

## Context

I'm using GitHub Pages, and my `Gemfile.lock` file specifies the following under `github-pages (213)`:
```
kramdown (= 2.3.0)
kramdown-parser-gfm (= 1.1.0)
```
And under `jekyll (3.9.0)`:
```
kramdown (>= 1.17, < 3)
```
and then also
```
    kramdown (2.3.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
```

My `_config.yml` includes the following lines:
```
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols: { hellip: ... , mdash: --- , ndash: -- , laquo: "<<" , raquo: ">>" , laquo_space: "<< " , raquo_space: " >>" }
  auto_id_stripping: true
```

I noticed that I didn't have a `markdown: kramdown` specified, but adding that in didn't change the behavior, so I'm thinking that maybe that becomes implicit if there's a `kramdown` object specified.

**Comment by ArthurZey** [comment]
FWIW, I've also confirmed the same behavior on [this online kramdown editor/renderer](http://kramdown.electricbook.works/), so it doesn't seem to be specific to a GitHub Pages or Jekyll implementation. 

It's a lot easier to see effects immediately if you include a TOC block:
```
* TOC
{:toc}
```

**Comment by gettalong** [comment]
So here is a complete example using your input data:

~~~
## 2021-03-30

## Foo
{: #bar}

## Foo {#bar}

## 2021-03-30: Foo {#2021-03-30}

## 2021-03-30: Foo
{: #2021-03-30}
~~~

Running that example file through the kramdown binary yields the following result:

~~~ html
<h2 id="section">2021-03-30</h2>

<h2 id="bar">Foo</h2>

<h2 id="bar">Foo</h2>

<h2 id="foo-2021-03-30">2021-03-30: Foo {#2021-03-30}</h2>

<h2 id="foo">2021-03-30: Foo</h2>
~~~

and the warning: *"Warning: No or invalid attributes found in IAL/ALD content:  #2021-03-30"*.

Reasons:

* Example 1 doesn't contain any letters, so the automatically generated ID is empty as per the documentation, and therefore `sectoin` is used.

* Examples 2 and 3 work as you expected.

* Example 4 and 5 work as intended: The first part "2021-03-30: " is stripped because the first letter is the "F" of "Foo".

Auto-ID generation for parser-gfm may be different, so please check there for file an issue there: https://github.com/kramdown/parser-gfm.

**Comment by ArthurZey** [comment]
Hey, @gettalong: Thank you so much for your prompt response and for going through that testing!

As you may have noticed, I did file https://github.com/kramdown/parser-gfm/issues/26, but I find myself curious about the kramdown binary behavior here. Perhaps it would be worthwhile to open a feature request, but I'd rather inquire with you first:

What is the reason that IDs can't start with numbers? At least in the case of URL anchors, it's valid and supported. Was there a particular motivation for excluding them for either manual specification or autogeneration?

Thank you again!
