### ISSUE TITLE
Accessibility: ARIA role doc-endnote is deprecated.

### ISSUE THREAD

**Issue by mejiaj** [gettalong/kramdown#729]
doc-backlink, doc-endnote, doc-endnotes, and doc-noteref should be removed and instead rely on native semantic elements like `<ol>, <ul>, and <li>`.

---

If you run the ARIA validator extension in Chrome on a page like:
https://designsystem.digital.gov/next/introduction/

You'll get the following:
![image](https://user-images.githubusercontent.com/3385219/134360104-aae1dd26-9107-484f-a05c-ca155e8a8074.png)

Per DPUB-ARIA 1.0 Recommendation:

>23-July-2020: Deprecated the doc-biblioentry and doc-endnote roles due to the inability of them to be recognized as children of list. See issue 15.

You can view the full changelog here: https://w3c.github.io/dpub-aria/#changelog

**Comment by BryceStevenWilley** [comment]
> doc-backlink, doc-endnote, doc-endnotes, and doc-noteref should be removed and instead rely on native semantic elements like `<ol>`, `<ul>`, and `<li>`.

The dpub ARIA 1.1 working draft that you linked [does mention that `doc-endnote` is deprecated](https://w3c.github.io/dpub-aria/#h-note-0), but it doesn't seem to mention the other roles (`doc-backlink`, `doc-endnotes`, and `doc-noteref`) as being deprecated at all.

[The ARIA validator extension](https://chrome.google.com/webstore/detail/aria-validator/oigghlanfjgnkcndchmnlnmaojahnjoc) hasn't been updated since 2014, and it's `code.google.com` repo links to [a newer chrome extension](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb), which itself is deprecated and links to [lighthouse's accessibility audit](https://developer.chrome.com/docs/lighthouse/accessibility/). Given that dpub-aria was first released in 2016, I don't think the aria validator extension would know about these roles, and would incorrectly mark them as "not existing". 

Removing `doc-endnote` would be simple, but I'm personally not sure how it's currently being used by accessibility technologies, and when it's deprecation would change from being a working draft to a W3C recommendation.

**Comment by ThomasOwens** [comment]
I'm curious if there's any update to this. It doesn't appear to be a huge impact, but it is being flagged for accessibility. From what I can understand, there are now two ways to handle endnotes.

In one approach, there is a `<div>` or `<section>` with the `role="doc-endnotes" aria-labelledby="note-hd"` attributes. Within this section, there is an `<ol>`, where each `<li>` has an ID corresponding to the identifier for the note. From what I can gather, this approach is mostly implemented in the Kramdown output. The `role="doc-endnote"` should be removed from the `<li>`s and everything else would be satisfied.

However, there's also an incompatible role involved in the link to the footnote. The `role="doc-noteref"` should be applied to the `<a>` tag and not the `<sup>` tag.

I believe these two changes will bring Kramdown to conform to scanning tools. But what I don't know is how well assistive technologies have implemented the recommendations.

**Comment by gettalong** [comment]
I have removed the `doc-endnote` role. The `doc-noteref` is already at the `<a>` tag due to another commit. This change will be live with the next release due within a week.
