### ISSUE TITLE
`time` should be span level by default

### ISSUE THREAD

**Issue by EtienneMiret** [gettalong/kramdown#794]
The below input:

```md
Please, make sure you will be available               
<time datetime="2023-10-14">next Saturday</time>.
```

generates:

```html
<p>Please, make sure you will be available</p>
<time datetime="2023-10-14">next Saturday</time>
<p>.</p>
```

(using kramdown 2.4.0 on ruby 3.2.2)

Which, well… is plain wrong.

Sure, the `time` element is not listed among the span level elements in the [kramdown syntax](https://kramdown.gettalong.org/syntax.html), so this may be a new feature rather than a bug. Yet, those 3 lists (raw HTML, block-level elements and span-level elements) need to be updated each time the HTML standard is updated. At least until #793 is supported.

**Comment by gettalong** [comment]
Thanks for the report! The `<time>` element could also be a block-level element but I agree that in kramdown it makes more sense as span-level element. I have fixed this so that it results in:

~~~ HTML
<p>Please, make sure you will be available
<time datetime="2023-10-14">next Saturday</time>.</p>
~~~
