### ISSUE TITLE
empty tables not handled sanely

### ISSUE THREAD

**Issue by gsar** [gettalong/kramdown#817]
following up on #802, there seem to be various inconsistencies in how empty tables or table elements are rendered.

![image](https://github.com/user-attachments/assets/e93a2fb8-3dc4-44dd-9ff4-ca35ad1c0789)

**Comment by gettalong** [comment]
Only the last of those lines describes a valid, empty table. All other lines are either missing the required elements completely or missing one or more end tags (as required by kramdown).

**Comment by gsar** [comment]
@gettalong would be great to understand the following:

* why is kramdown producing extra text in the invalid cases 3 and 5? i expect either exactly what was passed in, or the invalid nodes removed, not some extra invalid stuff added.
* case 1 adds a closing tag (with an extra newline) but the other cases don't, why?

thanks for any hints.

**Comment by gettalong** [comment]
ad case 1: It adds a closing because otherwise it would be invalid. You either have a closing tag or only a self-closing start tag. Note that even with the closing tag the element is invalid.

ad creating `<table />`: That could be seen as a bug because tables must not be written using a self-closing tag. However, a table without at least one row is also invalid.

ad cases 3 and 5: I'm not sure but again both cases are invalid so you wouldn't have a guarantee that the output gets suddenly valid.

**Comment by gsar** [comment]
@gettalong to be clear, i'm not expecting this gem to fix invalid markup, so i agree and am aligned with your "output can't become suddenly valid".

however, for the cases where the text i supplied _is_ being changed, i expect it to fix the markup _and_ convert it to markdown. in the cases where that's not possible, i expect the invalid nodes to either remain untouched or be completely removed. it is doing something in-between right now by both changing the text and not successfully converting it to markdown, which is neither here nor there.
